import type { Metadata } from "next";
import { Montserrat } from "next/font/google"
import "./globals.css";
import { Header } from "@/components";


const montserrat = Montserrat({
  subsets: ["cyrillic", "latin"],
  variable: "--font-montserrat"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${montserrat.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header />
        {children}</body>
    </html>
  );
}
